fieldLayouts:
  dffd8ab3-293a-465c-8012-212cf2163049:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4dce7230-33ed-48ed-a0eb-282a35d06668
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e674d4ca-c17d-405f-81ec-52e3f33bd2d0 # Product Brand
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77df0dde-99e1-4e65-82ae-c002ca4d8bde
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a5ac68a5-7d49-42e3-acad-1b4767bc31dd # Product Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57a42635-fbb4-4f55-b54a-b8b34589e836
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e8d22a20-c9ae-4c66-8549-5785f9701cc5 # Product Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 608b6981-5c7a-4969-a7b0-e462854d117f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77ed3694-98fe-460a-88b1-e12cd9e20787 # Product Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37c77e51-2c2c-41f2-9446-e0ea8ae594ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 86db85ad-8482-4e82-9713-af24bbb14e05 # Video Sections
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d25762f9-0055-4da6-9be9-dbefc023df9d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7621a0e9-e2a9-45e3-bdd6-ae3a5bb7e674
        userCondition: null
handle: product
hasTitleField: true
name: Product
section: 59bcce9b-0523-4c33-ac21-5c3a3879cfbe # Products
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
