fieldLayouts:
  b9af0856-cbf2-4e28-a2c6-a416aa77b54d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0849ebc3-989c-446d-a519-b3a032bec998
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e8d22a20-c9ae-4c66-8549-5785f9701cc5 # Product Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4476bacf-edcb-4474-9b2f-7f3cec116568
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ff8cdee-ebe4-488c-9b5c-4eefb0adccda # Quiz
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f31b9462-7d01-4967-83a0-b37f48d91e6f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b777d1e3-1c75-4c89-98ac-3c8aa73ece4b
        userCondition: null
handle: quiz
hasTitleField: true
name: Quiz
section: 59bcce9b-0523-4c33-ac21-5c3a3879cfbe # Products
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
