description: ''
handle: trainer
name: Trainer
permissions:
  - administrateusers
  - 'assignusergroup:b8bec7f1-2e09-4b73-b034-d67d1c224348' # Operator
  - deleteusers
  - editusers
  - moderateusers
  - registerusers
  - 'viewentries:59bcce9b-0523-4c33-ac21-5c3a3879cfbe' # Products
