columnSuffix: null
contentColumnType: string
fieldGroup: d3da2a31-6aef-4533-86ad-0cfb6924a6b1 # Products
handle: quiz
instructions: null
name: Quiz
searchable: false
settings:
  contentTable: '{{%matrixcontent_quiz}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
