columnSuffix: fapojhru
contentColumnType: boolean
fieldGroup: b957da5d-2360-4243-9f15-e94ef786cf21 # Users
handle: testPass
instructions: null
name: 'Test Pass'
searchable: false
settings:
  default: false
  offLabel: Failed
  onLabel: Passed
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
