columnSuffix: null
contentColumnType: string
fieldGroup: d3da2a31-6aef-4533-86ad-0cfb6924a6b1 # Products
handle: videoSections
instructions: null
name: 'Video Sections'
searchable: false
settings:
  contentTable: '{{%matrixcontent_videosections}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
