fieldLayouts:
  61d26434-9b08-41ef-8405-8af6297564cf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 2a41822b-a2d3-4589-86df-4c49281e98a9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d673449c-eb24-4356-8856-db049d780a24
        userCondition: null
fs: hardDisk
handle: productVideos
name: 'Product Videos'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
